import type { Metadata } from "next";
import { Rokkitt as RokkittFont } from "next/font/google"; // Renamed to avoid naming conflict
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

// Instantiate the font with the correct variable name and weight
const rokkitt = RokkittFont({
  subsets: ["latin"],
  weight: "400", // Specify the weight
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rokkitt.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
